$UPLOAD_ROOT  = ENV['PHOTOS_UPLOAD_ROOT']  || raise("ENV[PHOTOS_UPLOAD_ROOT] is required")
$GALLERY_ROOT = ENV['PHOTOS_GALLERY_ROOT'] || raise("ENV[PHOTOS_GALLERY_ROOT] is required")
$WORKING_PATH = ENV['PHOTOS_WORKING_PATH'] || raise("ENV[PHOTOS_WORKING_PATH] is required")
